-- =============================================================================
-- RAPOR_REKOMENDASI (Report Recommendations) Table
-- =============================================================================
-- Rule-based and expert recommendations targeted at specific roles
-- Tracks follow-up status and priority
-- =============================================================================

CREATE TABLE IF NOT EXISTS rapor_rekomendasi (
    -- Primary identifier
    id TEXT PRIMARY KEY NOT NULL,

    -- Reference to main rapor
    rapor_id TEXT NOT NULL,  -- References rapor_periode

    -- ==========================================================================
    -- Recommendation Details
    -- ==========================================================================

    -- Target audience
    untuk_peran TEXT NOT NULL CHECK(untuk_peran IN (
        'orang_tua',   -- For parents
        'mubaligh',    -- For teachers
        'pakar',       -- For experts
        'jamaah',      -- For the student themselves
        'semua'        -- For everyone
    )),

    -- Recommendation category
    kategori TEXT NOT NULL CHECK(kategori IN (
        'kehadiran',       -- Attendance-related
        'akademik',        -- Academic/subject-related
        'akhlaq',          -- Character-related
        'kelas_mandiri',   -- Parent self-learning
        'kesehatan',       -- Health-related
        'umum'             -- General
    )),

    -- Recommendation content
    judul TEXT NOT NULL,
    rekomendasi_text TEXT NOT NULL,
    alasan TEXT,  -- Reason for this recommendation

    -- Action items
    langkah_tindakan TEXT,  -- Step-by-step action
    target_tindak_lanjut TEXT,  -- Target/goal of follow-up
    durasi_target TEXT,  -- e.g., '1 minggu', '1 bulan'
    tanggal_target TEXT,

    -- Priority
    prioritas TEXT DEFAULT 'normal' CHECK(prioritas IN (
        'rendah',    -- Low priority
        'normal',    -- Normal priority
        'tinggi',    -- High priority
        'urgent'     -- Urgent
    )),

    -- Status tracking
    status_tindak_lanjut TEXT DEFAULT 'pending' CHECK(status_tindak_lanjut IN (
        'pending',      -- Not started
        'in_progress',  -- In progress
        'selesai',      -- Completed
        'dibatalkan'    -- Cancelled
    )),
    tanggal_mulai TEXT,
    tanggal_selesai TEXT,
    catatan_progress TEXT,

    -- Source of recommendation
    sumber TEXT CHECK(sumber IN (
        'sistem',      -- Auto-generated by rules
        'mubaligh',    -- From teacher
        'pakar',       -- From expert
        'manual'       -- Manual entry
    )),
    rule_id TEXT,  -- Reference to rule that generated this (if sistem)

    -- Author (for manual recommendations)
    dibuat_oleh TEXT,
    nama_pembuat TEXT,

    -- ==========================================================================
    -- Sync & Audit Fields
    -- ==========================================================================
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    last_modified TEXT NOT NULL DEFAULT (datetime('now')),
    sync_version INTEGER NOT NULL DEFAULT 1,
    is_deleted INTEGER NOT NULL DEFAULT 0,
    device_id TEXT
);

-- =============================================================================
-- RAPOR_REKOMENDASI_PROGRESS (Recommendation Progress Log)
-- Tracks progress updates for each recommendation
-- =============================================================================

CREATE TABLE IF NOT EXISTS rapor_rekomendasi_progress (
    id TEXT PRIMARY KEY NOT NULL,
    rekomendasi_id TEXT NOT NULL,  -- References rapor_rekomendasi

    -- Progress entry
    tanggal TEXT NOT NULL,
    deskripsi TEXT NOT NULL,
    pencapaian TEXT,

    -- Who reported
    dilaporkan_oleh TEXT,
    nama_pelapor TEXT,
    peran_pelapor TEXT,

    -- Progress level
    tingkat_kemajuan TEXT CHECK(tingkat_kemajuan IN (
        'belum_mulai',
        'awal',
        'pertengahan',
        'hampir_selesai',
        'selesai'
    )),

    -- ==========================================================================
    -- Sync & Audit Fields
    -- ==========================================================================
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    last_modified TEXT NOT NULL DEFAULT (datetime('now')),
    sync_version INTEGER NOT NULL DEFAULT 1,
    is_deleted INTEGER NOT NULL DEFAULT 0,
    device_id TEXT
);

-- =============================================================================
-- Indexes
-- =============================================================================
CREATE INDEX IF NOT EXISTS idx_rapor_rekomendasi_rapor ON rapor_rekomendasi(rapor_id);
CREATE INDEX IF NOT EXISTS idx_rapor_rekomendasi_peran ON rapor_rekomendasi(untuk_peran);
CREATE INDEX IF NOT EXISTS idx_rapor_rekomendasi_kategori ON rapor_rekomendasi(kategori);
CREATE INDEX IF NOT EXISTS idx_rapor_rekomendasi_prioritas ON rapor_rekomendasi(prioritas);
CREATE INDEX IF NOT EXISTS idx_rapor_rekomendasi_status ON rapor_rekomendasi(status_tindak_lanjut);
CREATE INDEX IF NOT EXISTS idx_rapor_rekomendasi_last_modified ON rapor_rekomendasi(last_modified);

CREATE INDEX IF NOT EXISTS idx_rapor_rekomendasi_progress_rek ON rapor_rekomendasi_progress(rekomendasi_id);
CREATE INDEX IF NOT EXISTS idx_rapor_rekomendasi_progress_tanggal ON rapor_rekomendasi_progress(tanggal);

-- =============================================================================
-- Triggers for auto-update timestamps
-- =============================================================================
CREATE TRIGGER IF NOT EXISTS trg_rapor_rekomendasi_updated_at
AFTER UPDATE ON rapor_rekomendasi
FOR EACH ROW
BEGIN
    UPDATE rapor_rekomendasi
    SET updated_at = datetime('now'),
        last_modified = datetime('now'),
        sync_version = OLD.sync_version + 1
    WHERE id = NEW.id;
END;

CREATE TRIGGER IF NOT EXISTS trg_rapor_rekomendasi_progress_updated_at
AFTER UPDATE ON rapor_rekomendasi_progress
FOR EACH ROW
BEGIN
    UPDATE rapor_rekomendasi_progress
    SET updated_at = datetime('now'),
        last_modified = datetime('now'),
        sync_version = OLD.sync_version + 1
    WHERE id = NEW.id;
END;
